name: Phil
spring:
  datasource:
    url: jdbc:mysql://kashiyuka/perfume
    username: root
    password: perfume
    driverClassName: com.mysql.jdbc.Driver

  data:
      redis:
          host: nocchi
          port: 6379
          password: null
          database: 0
          pool:
              max-idle: 8
              min-idle: 0
              max-active: 8
              max-wait: -1