name: Phil
spring:
  datasource:
    url: jdbc:mysql://localhost/shuffle_lunch
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

  data:
      redis:
          host: localhost
          port: 6379
          password: null
          database: 0
          pool:
              max-idle: 8
              min-idle: 0
              max-active: 8
              max-wait: -1